/*
# This file is deprecated. Tools should instead consume
# `.dart_tools/package_config.json`.
# 
# For more info see: https://dart.dev/go/dot-packages-deprecation
# 
# Generated by pub on 2021-08-17 22:27:10.281843.
_fe_analyzer_shared:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-22.0.0/lib/
analyzer:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.7.1/lib/
args:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/args-2.1.1/lib/
async:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/async-2.6.1/lib/
boolean_selector:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/boolean_selector-2.1.0/lib/
build:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/build-2.0.2/lib/
build_config:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/build_config-1.0.0/lib/
build_daemon:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/
build_resolvers:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/build_resolvers-2.0.3/lib/
build_runner:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-2.0.5/lib/
build_runner_core:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner_core-7.0.0/lib/
built_collection:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/built_collection-5.1.0/lib/
built_value:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/built_value-8.1.0/lib/
cached_network_image:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.0.0/lib/
carousel_slider:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/carousel_slider-3.0.0/lib/
characters:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/characters-1.1.0/lib/
charcode:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/charcode-1.2.0/lib/
checked_yaml:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/checked_yaml-2.0.1/lib/
cli_util:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/cli_util-0.3.1/lib/
clock:file:///C:/flutter_windows_1.22.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org*/
