import 'package:get_storage/get_storage.dart';
import 'package:shared_preferences/shared_preferences.dart';

class SharedConfig {
  static SharedPreferences pref;
}


final boxStorage=GetStorage();

const String KEY_TOKEN="TOKEN";
const String KEY_USER_ID="USER_ID";
const String KEY_USER_NAME="USER_NAME";
const String KEY_USER_PHONE = "USER_PHONE";
const String KEY_USER_EMAIL = "USER_EMAIL";
const String KEY_USER_ADDRESS = "USER_ADDRESS";
const String KEY_USER_CITY = "USER_CITY";
const String KEY_USER_COUNTRY = "USER_COUNTRY";
const String KEY_USER_GENDER = "USER_GENDER";
const String KEY_USER_BIRTHDAY = "USER_BIRTHDAY";
const String KEY_USER_STATUS = "USER_STATUS";
const String KEY_USER_AVATAR = "USER_AVATAR";
const String KEY_USER_CREATED_AT = "USER_CREATED_AT";
const String KEY_USER_UPDATED_AT = "USER_UPDATED_AT";

///Business Info
const String MY_BUSINESS_NAME="MY_BUSINESS_NAME";
const String MY_BUSINESS_SLUG="MY_BUSINESS_SLUG";
const String MY_BUSINESS_ID="MY_BUSINESS_ID";

///Version Number
const String VERSION_NUMBER="VERSION_NUMBER";

///lAT & lANG
const String LAT="lat";
const String LONG="long";

///User business Data
const String KEY_USER_BUSINESS_NAME="BUSINESS_NAME";
const String KEY_USER_STREET_ADDRESS="BUSINESS_STREETADRESS";
const String KEY_USER_LANDMARK="BUSINESS_LANDMARK";
const String KEY_USER_BUILDING="BUSINESS_BUILDING";
const String KEY_USER_THANA_ID="BUSINESS_THANA_ID";
const String KEY_USER_POSTAL_CODE="BUSINESS_POSTAL_CODE";
const String KEY_USER_AREA_ID="BUSINESS_AREA";
const String KEY_USER_PLUS_CODE="BUSINESS_PLUS_CODE";
const String KEY_USER_AREA = "USER_AREA";
const String KEY_BUSINESS_OWNER_NAME = "BUSINESS_OWNER_NAME";
const String KEY_BUSINESS_OWNER_TITLE = "BUSINESS_OWNER_TITLE";
const String KEY_BUSINESS_DESIGNATION = "BUSINESS_DESIGNATION";
const String KEY_BUSINESS_PHONE_NUMBER = "BUSINESS_PHONE_NUMBER";
const String KEY_BUSINESS_FAX = "BUSINESS_FAX";
const String KEY_BUSINESS_WEBSITE = "BUSINESS_WEBSITE";
const String KEY_BUSINESS_FACEBOOK = "BUSINESS_FACEBOOK";
const String KEY_BUSINESS_TWITTER = "BUSINESS_TWITTER";
const String KEY_BUSINESS_EMAIL = "BUSINESS_EMAIL";

const String MOBILE_ONE="MOBILE_ONE";
const String MOBILE_TWO="MOBILE_TWO";
const String MOBILE_THREE="MOBILE_THREE";
const String MOBILE_NUMBERS="MOBILE_NUMBERS";

const String BUSINESS_OPEN_TIME="BUSINESS_OPEN_TIME";
const String BUSINESS_CLOSE_TIME="BUSINESS_CLOSE_TIME";


const String SAT_START="SAT_START";
const String SAT_END="SAT_END";
const String SUN_START="SUN_START";
const String SUN_END="SUN_END";
const String MON_START="MON_START";
const String MON_END="MON_END";
const String TUE_START="TUE_START";
const String TUE_END="TUE_END";
const String WED_START="WED_START";
const String WED_END="WED_END";
const String THURS_START="THURS_START";
const String THURS_END="THURS_END";
const String FRI_START="FRI_START";
const String FRI_END="FRI_END";

const String PAYMENT_ID_LIST="PAYMENT_ID_LIST";

const String YEAR_ESTABLISH="YEAR_ESTABLISH";
const String ANNUAL_TURNOVER="ANNUAL_TURNOVER";
const String NUMBER_OF_EMPLOYEE="NUMBER_OF_EMPLOYEE";
const String PROFESSIONAL_ASSOC="PROFESSIONAL_ASSOC";
const String CERTIFICATION="CERTIFICATION";
const String DESCRIPTION="DESCRIPTION";
const String TYPE_OF_BUSINESS="TYPE_OF_BUSINESS";


const String QUESTION_ONE="QUESTION_ONE";
const String QUESTION_TWO="QUESTION_TWO";
const String QUESTION_THREE="QUESTION_THREE";
const String QUESTION_FOUR="QUESTION_FOUR";
const String ANSWER_ONE="ANSWER_ONE";
const String ANSWER_TWO="ANSWER_TWO";
const String ANSWER_THREE="ANSWER_THREE";
const String ANSWER_FOUR="ANSWER_FOUR";

const String SEO_TITLE="SEO_TITLE";
const String META_DESCRIPTION="META_DESCRIPTION";
const String TAG_LIST="TAG_LIST";
const String KEYWORDS="KEYWORDS";
const String MORE_PHOTOS="COVER_PHOTOS";
const String DEVICE_IPI="DEVICE_API";
const String SESSION_ID="SESSION_ID";
const String SAVE_OTP="SAVE_OTP";



