import 'package:get_storage/get_storage.dart';
import 'package:shared_preferences/shared_preferences.dart';

class SharedConfig {
  static SharedPreferences pref;
}


final boxStorage=GetStorage();

const String KEY_TOKEN="TOKEN";
const String KEY_USER_ID="USER_ID";
const String KEY_USER_NAME="USER_NAME";
const String KEY_USER_PHONE = "USER_PHONE";
const String KEY_USER_EMAIL = "USER_EMAIL";
const String KEY_USER_ADDRESS = "USER_ADDRESS";
const String KEY_USER_CITY = "USER_CITY";
const String KEY_USER_COUNTRY = "USER_COUNTRY";
const String KEY_USER_GENDER = "USER_GENDER";
const String KEY_USER_BIRTHDAY = "USER_BIRTHDAY";
const String KEY_USER_STATUS = "USER_STATUS";
const String KEY_USER_AVATAR = "USER_AVATAR";
const String KEY_USER_CREATED_AT = "USER_CREATED_AT";
const String KEY_USER_UPDATED_AT = "USER_UPDATED_AT";


///User business Data
const String KEY_USER_BUSINESS_NAME="BUSINESS_NAME";
const String KEY_USER_STREET_ADDRESS="BUSINESS_NAME";
const String KEY_USER_LANDMARK="BUSINESS_NAME";
const String KEY_USER_BUILDING="BUSINESS_NAME";
const String KEY_USER_THANA_ID="BUSINESS_NAME";
const String KEY_USER_POSTAL_ID="BUSINESS_NAME";
const String KEY_USER_AREA_ID="BUSINESS_NAME";
const String KEY_USER_PLUS_CODE="BUSINESS_NAME";
const String KEY_USER_AREA = "USER_AREA";
const String KEY_BUSINESS_OWNER_NAME = "BUSINESS_OWNER_NAME";
const String KEY_BUSINESS_OWNER_TITLE = "BUSINESS_OWNER_TITLE";
const String KEY_BUSINESS_DESIGNATION = "BUSINESS_DESIGNATION";
const String KEY_BUSINESS_PHONE_NUMBER = "BUSINESS_PHONE_NUMBER";
const String KEY_BUSINESS_FAX = "BUSINESS_FAX";
const String KEY_BUSINESS_WEBSITE = "BUSINESS_WEBSITE";
const String KEY_BUSINESS_FACEBOOK = "BUSINESS_FACEBOOK";
const String KEY_BUSINESS_TWITTER = "BUSINESS_TWITTER";
const String KEY_BUSINESS_EMAIL = "BUSINESS_EMAIL";

const String SAT_START="SAT_START";
const String SAT_END="SAT_END";
const String SUN_START="SUN_START";
const String SUN_END="SUN_END";
const String MON_START="MON_START";
const String MON_END="MON_END";
const String TUE_START="TUE_START";
const String TUE_END="TUE_END";
const String WED_START="WED_START";
const String WED_END="WED_END";
const String THURS_START="THURS_START";
const String THURS_END="THURS_END";
const String FRI_START="FRI_START";
const String FRI_END="FRI_END";

const String PAYMENT_ID_LIST="PAYMENT_ID_LIST";

const String YEAR_ESTABLISH="YEAR_ESTABLISH";
const String ANNUAL_TURNOVER="ANNUAL_TURNOVER";
const String NUMBER_OF_EMPLOYEE="NUMBER_OF_EMPLOYEE";
const String PROFESSIONAL_ASSOC="PROFESSIONAL_ASSOC";
const String CERTIFICATION="CERTIFICATION";
const String DESCRIPTION="DESCRIPTION";
const String TYPE_OF_BUSINESS="TYPE_OF_BUSINESS";


