import 'package:get_storage/get_storage.dart';
import 'package:shared_preferences/shared_preferences.dart';


final boxNewStorage=GetStorage();

const String Business_Building="Business_Building";
const String Business_NAME="Business_Name";
const String Business_LANDMARK="Business_LANDMARK";
const String Business_PLUSCODE="Business_PLUSCODE";
const String Business_LOCATION="LOCATION";
const String Business_TYPE="BUSINESS_TYPE";

const String BUSINESS_LAND_LINE="BUSINESS_LANDLING";
const String BUSINESS_MOBILE_NUMBERS="BUSINESS_MOBILE_NUMBERS";
const String OWNER_NAME="OWNER_NAME";
const String OWNER_TITLE="OWNER_TITLE";
const String OWNER_WEBSITE="OWNER_WEBSITE";
const String OWNER_EMAIL="OWNER_EMAIL";

///Operation hour
const String BUSINESS_MONDAY_START="MONDAY_START";
const String BUSINESS_SUNDAY_START="SUNDAY_START";
const String BUSINESS_TUESDAY_START="TUESDAY_START";
const String BUSINESS_WEDNESDAY_START="WEDNESDAY_START";
const String BUSINESS_THURSDAY_START="THURSDAY_START";
const String BUSINESS_FRIDAY_START="FRIDAY_START";
const String BUSINESS_SATURDAY_START="SATURDAY_START";

const String BUSINESS_MONDAY_END="MONDAY_END";
const String BUSINESS_SUNDAY_END="SUNDAY_END";
const String BUSINESS_TUESDAY_END="TUESDAY_END";
const String BUSINESS_WEDNESDAY_END="WEDNESDAY_END";
const String BUSINESS_THURSDAY_END="THURSDAY_END";
const String BUSINESS_FRIDAY_END="FRIDAY_END";
const String BUSINESS_SATURDAY_END="SATURDAY_END";

///Others
const String BUSINESS_PROFESSIONAL_ASSOCIATION="PROFESSIONAL_ASSOCIATION";
const String BUSINESS_PROFESSIONAL_CERTIFICATION="PROFESSIONAL_CERTIFICATION";
const String BUSINESS_PROFESSIONAL_PAYMENT_METHOD="PROFESSIONAL_PAYMENT_METHOD";
const String BUSINESS_PROFESSIONAL_PAYMENT_METHOD_NAME="PROFESSIONAL_PAYMENT_METHOD_NAME";
const String BUSINESS_KEYWORDS="BUSINESS_KEYWORDS";
const String BUSINESS_TAGS="BUSINESS_TAGS";
const String BUSINESS_DESCRIPTION="BUSINESS_DESCRIPTION";
const String BUSINESS_YEARS_ESTABLISH="BUSINESS_YEARS_ESTABLISH";
const String BUSINESS_META_TITLE="BUSINESS_META_TITLE";
const String BUSINESS_META_DESC="BUSINESS_META_DESC";







